name: aghamazing1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  lottie: ^3.3.2
  http: ^1.6.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.2
  camera: ^0.11.0+2
  google_mlkit_text_recognition: ^0.13.0
  permission_handler: ^11.3.1
  intl: ^0.18.1
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/pngs/
    - assets/images/backgrounds/
    - assets/images/avatars/
    - assets/animations/
    - assets/config/
    - assets/images/jpgs/
